pipeline {
    agent {
        label 'worker-1'
    }

    stages {
        stage('Shell Test') {
            steps {
                sh '''
                    set -eux
                    whoami
                    id
                    pwd
                    echo "Jenkins shell execution is working"
                    java -version
                    git --version
                    df -h
                    df -i
                    mount | grep -E " /home | / "
                '''
            }
        }
    }
}